name: Test Worker
on:
  push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Create testing env
        env: # Or as an environment variable
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "API_KEY=\"$API_KEY\"" > .dev.vars
      - name: Start Headless
        run: npx wrangler dev --port 3000 < /dev/null &
      
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "33304115-bf5ed4f7-1e01-45cf-927a-ed65a4c0e565" -e "33304115-8ac97ab4-ef85-46db-b9b8-bf41e4c2b1b9"

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build & Deploy Worker
  #       uses: cloudflare/wrangler-action@v3
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
